name: ChatGPT Code Review

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ChatGPT Code Review
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.BOO_BABA }}
          OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PULL_NUMBER: ${{ github.event.pull_request.number }}
